language: java
jdk:
  - oraclejdk8
sudo: enabled
services:
  - mysql
before_install:
  - mysql -e 'DROP DATABASE IF EXISTS bug;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS bug;'
  - mysql < "bug_db.sql"
script: mvn clean verify